version: "2"

services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  base-go:
    image: base-go:latest
    build: .
    depends_on:
      - mariadb
    restart: on-failure:3
    ports:
      - "5000:5000"
    command:
      - -db-host=mariadb
